# Generated by Django 5.1.15 on 2026-08-31 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('phase', models.CharField(choices=[('বেসিক টু এডভান্স', 'বেসিক টু এডভান্স'), ('ফাইনাল রিভিশন', 'ফাইনাল রিভিশন'), ('কুইক রিভিশন', 'কুইক রিভিশন'), ('মডেল টেস্ট', 'মডেল টেস্ট')], max_length=40)),
                ('subject', models.CharField(blank=True, max_length=80)),
                ('lecture', models.CharField(blank=True, max_length=120)),
                ('bsc_topic', models.TextField(blank=True)),
                ('diploma_topic', models.TextField(blank=True)),
                ('live_class_link', models.URLField(blank=True, max_length=500)),
                ('question_bank_link', models.URLField(blank=True, max_length=500)),
                ('exam_link', models.URLField(blank=True, max_length=500)),
                ('book_link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(db_index=True, max_length=20, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.dayroutine')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='challenge.student')),
            ],
            options={
                'unique_together': {('student', 'routine')},
            },
        ),
    ]
